In [10]:
#Import libraries
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
#Import the Dataset
data = pd.read_csv("Book_Recommend_Dataset.csv")

In [3]:
#Load the Dataset
data.head()

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,https://m.media-amazon.com/images/I/713KZTsaYp...,https://www.amazon.com/dp/B00TZE87S4,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,https://m.media-amazon.com/images/I/A1LZcJFs9E...,https://www.amazon.com/dp/B08WCKY8MB,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,https://m.media-amazon.com/images/I/71RIWM0sv6...,https://www.amazon.com/dp/B09KPS84CJ,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,https://m.media-amazon.com/images/I/71QdQpTiKZ...,https://www.amazon.com/dp/B07S7QPG6J,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,https://m.media-amazon.com/images/I/813o4WOs+w...,https://www.amazon.com/dp/B00N6PEQV0,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships

In [4]:
#Check the Info Of the Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133102 entries, 0 to 133101
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   asin               133102 non-null  object
 1   title              133102 non-null  object
 2   author             132677 non-null  object
 3   soldBy             123869 non-null  object
 4   imgUrl             133102 non-null  object
 5   productURL         133102 non-null  object
 6   stars              133102 non-null  float64
 7   reviews            133102 non-null  int64
 8   price              133102 non-null  float64
 9   isKindleUnlimited  133102 non-null  bool
 10  category_id        133102 non-null  int64
 11  isBestSeller       133102 non-null  bool
 12  isEditorsPick      133102 non-null  bool
 13  isGoodReadsChoice  133102 non-null  bool
 14  publishedDate      84086 non-null   object
 15  category_name      133102 non-null  object
dtypes: bool(4), float64(2), int64(2), object(8)
memory usage: 12.7+ MB

In [5]:
#Check the Shape of Dataset
data.shape

(133102, 16)

In [11]:
#Remove Unsed Columns
data = data[['title','author','soldBy','publishedDate','imgUrl']]

In [12]:
#Load new Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133102 entries, 0 to 133101
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   title          133102 non-null  object
 1   author         132677 non-null  object
 2   soldBy         123869 non-null  object
 3   publishedDate  84086 non-null   object
 4   imgUrl         133102 non-null  object
dtypes: object(5)
memory usage: 5.1+ MB

In [13]:
#Check the Empty Values
data.isnull().sum()

title                0
author             425
soldBy            9233
publishedDate    49016
imgUrl               0
dtype: int64

In [14]:
data.isnull().sum()

title                0
author             425
soldBy            9233
publishedDate    49016
imgUrl               0
dtype: int64

In [15]:
#Remove the Duplicate Values
data.drop_duplicates(subset=['author'],inplace=True)
#Remove the Duplicate Values
data.drop_duplicates(subset=['soldBy'],inplace=True)
#Remove the Duplicate Values
data.drop_duplicates(subset=['publishedDate'],inplace=True)

In [16]:
#Check the Status Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 78886
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          28 non-null     object
 1   author         28 non-null     object
 2   soldBy         27 non-null     object
 3   publishedDate  27 non-null     object
 4   imgUrl         28 non-null     object
dtypes: object(5)
memory usage: 1.3+ KB

In [17]:
#Check the columns data status
data.author.unique()

array(['Lindsay C. Gibson', 'Arthur C. Brooks', 'Becky Kennedy',
       'John Gottman', 'Jeannette Walls', 'Oprah Winfrey',
       'Heidi Murkoff', 'Robert F. Kennedy Jr.', 'Colleen Hoover',
       'Justin Whitmel Earley', 'L. M. Montgomery', 'Maria Tatar',
       'Amanda Montei', 'Teresa M. McDevitt', 'Belinda Daughrity',
       'Mitch Weiss', 'Rachel Marks', 'Kasey Edwards',
       'Michelle Mitchell', 'Roberta M. Berns', 'Kris Bordessa',
       'Fletcher McKenzie', 'Mark Millhone', 'Ali Amrabet',
       'Inès de La Fressange', 'Jill Leovy', 'Sarah Albee', 'Matt Perman'],
      dtype=object)

In [18]:
#Check the columns data status
data.soldBy.unique()

array(['Amazon.com Services LLC', 'Penguin Group (USA) LLC',
       'HarperCollins Publishers', 'Random House LLC',
       'Simon and Schuster Digital Sales Inc', 'Macmillan',
       'Hachette Book Group', 'Simon & Schuster Digital Sales Inc.', nan,
       'HarperCollins Publishing', 'De Marque', 'W. W. Norton & Company',
       'Penguin Random House Publisher Services',
       'Pearson Education,Inc.', 'JOHN WILEY AND SONS INC',
       'Harlequin Digital Sales Corp.', 'PRH UK', 'RH AU',
       'Penguin Random House Australia Pty Ltd', 'Cengage Learning',
       'Disney Book Group', 'Random House NZ', 'Amazon.com',
       'Gallimard Lt.', 'Flammarion Lt.',
       'Amazon Digital Services LLC HN', 'Scholastic Trade Publisher',
       'Amazon Digital Services LLC MK'], dtype=object)

In [19]:
#Check the columns data status
data.title.unique()

array(['Adult Children of Emotionally Immature Parents: How to Heal from Distant, Rejecting, or Self-Involved Parents',
       'From Strength to Strength: Finding Success, Happiness, and Deep Purpose in the Second Half of Life',
       'Good Inside: A Guide to Becoming the Parent You Want to Be',
       "The Seven Principles for Making Marriage Work: A Practical Guide from the Country's Foremost Relationship Expert",
       'The Glass Castle: A Memoir',
       'What Happened to You?: Conversations on Trauma, Resilience, and Healing',
       "What to Expect When You're Expecting",
       'Vax-Unvax: Let the Science Speak (Children’s Health Defense)',
       'It Starts with Us: the highly anticipated sequel to IT ENDS WITH US',
       'Habits of the Household: Practicing the Story of God in Everyday Family Rhythms',
       'Anne Of Green Gables Complete 8 Book Set',
       'The Classic Fairy Tales (Second Edition) (Norton Critical Editions)',
       'Touched Out: Motherhood, Misogyny, Consent, and Control',
       'Child Development and Education',
       'Autism Spectrum Disorders from Theory to Practice: Assessment and Intervention Tools Across the Lifespan',
       "Broken Faith: Inside one of America's Most Dangerous Cults",
       'Saturdays at Noon: An uplifting, emotional and unpredictable page-turner to make you smile',
       'Raising Girls Who Like Themselves', 'Tweens',
       'Child, Family, School, Community: Socialization and Support',
       'Attainable Sustainable: The Lost Art of Self-Reliant Living',
       "From the Pilot's Seat: Kiwi Adventurers in the Sky",
       'The Patron Saint of Used Cars and Second Chances: A Memoir',
       'Draw and animate your manga characters: The Complete Guide by @ZESENSEI_DRAWS',
       'Parisian Chic - Look Book: What should I wear today ?',
       'Ghettoside: A True Story of Murder in America',
       'Accidental Archaeologists: True Stories of Unexpected Discoveries',
       "What's Best Next: How the Gospel Transforms the Way You Get Things Done"],
      dtype=object)

In [20]:
#Check the columns data status
data.publishedDate.unique()

array(['2015-06-01', '2022-02-15', '2022-09-13', '2015-05-05',
       '2005-03-01', '2021-04-27', nan, '2023-08-29', '2022-10-18',
       '2021-11-09', '2023-09-25', '2017-01-20', '2023-09-12',
       '2019-03-01', '2022-11-22', '2020-02-18', '2020-02-06',
       '2021-02-02', '2023-02-28', '2015-01-01', '2020-04-28',
       '2023-08-01', '2008-07-07', '2023-05-26', '2017-04-05',
       '2015-01-27', '2020-11-10', '2014-03-04'], dtype=object)

In [21]:
# Assuming your data is in a DataFrame called 'data'
# Extract year from 'publishedDate' column
data['year'] = pd.to_datetime(data['publishedDate']).dt.year

# Display the unique years
unique_years = data['year'].unique()
print(unique_years)

[2015. 2022. 2005. 2021.   nan 2023. 2017. 2019. 2020. 2008. 2014.]

In [22]:
#Check the Status Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 78886
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          28 non-null     object
 1   author         28 non-null     object
 2   soldBy         27 non-null     object
 3   publishedDate  27 non-null     object
 4   imgUrl         28 non-null     object
 5   year           27 non-null     float64
dtypes: float64(1), object(5)
memory usage: 1.5+ KB

In [25]:
#Combination of colums
data['MetaData'] = data['title'] + data['author'] + data['soldBy']

In [26]:
#Reload the Dataset
data.head()

,title,author,soldBy,publishedDate,imgUrl,year,text,MetaData
0,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,2015-06-01,https://m.media-amazon.com/images/I/713KZTsaYp...,2015.0,Adult Children of Emotionally Immature Parents...,Adult Children of Emotionally Immature Parents...
1,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,2022-02-15,https://m.media-amazon.com/images/I/A1LZcJFs9E...,2022.0,"From Strength to Strength: Finding Success, Ha...","From Strength to Strength: Finding Success, Ha..."
2,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,2022-09-13,https://m.media-amazon.com/images/I/71RIWM0sv6...,2022.0,Good Inside: A Guide to Becoming the Parent Yo...,Good Inside: A Guide to Becoming the Parent Yo...
4,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,2015-05-05,https://m.media-amazon.com/images/I/813o4WOs+w...,2015.0,The Seven Principles for Making Marriage Work:...,The Seven Principles for Making Marriage Work:...
5,The Glass Castle: A Memoir,Jeannette Walls,Simon and Schuster Digital Sales Inc,2005-03-01,https://m.media-amazon.com/images/I/71td5GDUZM...,2005.0,The Glass Castle: A MemoirJeannette WallsSimon...,The Glass Castle: A MemoirJeannette WallsSimon...